# Generated by Django 5.0.2 on 2024-03-02 13:53

import api.validators.StudentValidator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=10, unique=True, validators=[api.validators.StudentValidator.rollNo])),
                ('name', models.CharField(max_length=255)),
                ('emailId', models.EmailField(max_length=255, unique=True, validators=[api.validators.StudentValidator.email])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('CB', 'CB'), ('ECE', 'ECE'), ('HCD', 'HCD'), ('SSH', 'SSH'), ('MATHS', 'MATHS')], max_length=10)),
                ('joiningDate', models.DateField()),
                ('batch', models.CharField(help_text='Use the following format: Month YYYY', max_length=20, validators=[api.validators.StudentValidator.batch])),
                ('educationalQualification', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Outside Delhi', 'Outside Delhi')], max_length=15, null=True)),
                ('admissionThrough', models.CharField(choices=[('Regular', 'Regular'), ('Rolling', 'Rolling'), ('Sponsored', 'Sponsored'), ('Migrated', 'Migrated'), ('Direct', 'Direct')], max_length=10)),
                ('fundingType', models.CharField(choices=[('Institute', 'Institute'), ('Sponsored', 'Sponsored'), ('Others', 'Others')], max_length=10)),
                ('sourceOfFunding', models.CharField(blank=True, max_length=255, null=True)),
                ('contingencyPoints', models.PositiveIntegerField(default=20000)),
                ('studentStatus', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Graduated', 'Graduated'), ('Shifted', 'Shifted'), ('Semester Leave', 'Semester Leave')], default='Active', max_length=15)),
                ('thesisSubmissionDate', models.DateField(blank=True, null=True)),
                ('thesisDefenceDate', models.DateField(blank=True, null=True)),
                ('yearOfLeaving', models.PositiveIntegerField(blank=True, help_text='Use the following format: YYYY', null=True, validators=[django.core.validators.MinValueValidator(2000)])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipendMonths', models.PositiveIntegerField(default=0)),
                ('contingencyYears', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_details', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReview', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('comprehensiveReviewFile', models.FileField(max_length=255, upload_to='comprehensive_review_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_review', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorType', models.CharField(choices=[('Advisor-1', 'Advisor-1'), ('Advisor-2', 'Advisor-2'), ('Co-Advisor', 'Co-Advisor')], max_length=255)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to='api.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_set', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReview', models.DateField()),
                ('reviewYear', models.PositiveIntegerField(help_text='Enter the review year as a number (e.g., 1, 2, 3, etc.)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('yearlyReviewreviewFile', models.FileField(max_length=255, upload_to='yearly_review_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reviews', to='api.student')),
            ],
        ),
    ]
