# Generated by Django 5.0.2 on 2024-03-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['student']},
        ),
        migrations.AlterField(
            model_name='advisor',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_set', to='api.student'),
        ),
    ]
