# Generated by Django 5.0.2 on 2024-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contingencylogs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='contingencyYears',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
