# Generated by Django 5.0.2 on 2024-04-28 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comprehensive_options_alter_finance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipend',
            name='baseAmount',
            field=models.DecimalField(decimal_places=2, default=37000, max_digits=11, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stipend',
            name='hostler',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='stipend',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
