# Generated by Django 5.0.2 on 2024-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comprehensive_options_alter_finance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('roomNo', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('building', 'roomNo')},
            },
        ),
    ]
