# Generated by Django 5.0.2 on 2024-04-28 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stipend_baseamount_stipend_hostler_stipend_hra'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipend',
            name='month',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='stipend',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='stipend',
            name='disbursmentDate',
            field=models.DateField(default=datetime.date(2024, 4, 28)),
        ),
    ]
