# Generated by Django 5.0.2 on 2024-04-28 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stipend_month_stipend_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipend',
            name='disbursmentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 3, 18, 49, 143771, tzinfo=datetime.timezone.utc)),
        ),
    ]
