# Generated by Django 5.0.2 on 2024-04-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stipend_disbursmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stipend',
            name='amount',
        ),
    ]
