# Generated by Django 5.0.2 on 2024-04-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_stipend_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contingencyYears',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='student',
            name='stipendMonths',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
