# Generated by Django 5.0.2 on 2024-04-28 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_contingencyyears_student_stipendmonths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipend',
            name='disbursmentDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
