# Generated by Django 5.0.2 on 2024-04-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stipend_disbursmentdate'),
        ('api', '0009_alter_stipend_unique_together'),
    ]

    operations = [
    ]
