# Generated by Django 5.0.2 on 2024-04-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stipend_disbursmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyreview',
            old_name='yearlyReviewreviewFile',
            new_name='yearlyReviewFile',
        ),
    ]
