# Generated by Django 5.0.2 on 2024-04-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_yearlyreviewreviewfile_yearlyreview_yearlyreviewfile'),
        ('api', '0011_alter_stipend_disbursmentdate'),
    ]

    operations = [
    ]
