# Generated by Django 5.0.2 on 2024-05-13 17:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_stipend_disbursmentdate_alter_stipend_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingencylogs',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingencyLogs', to='api.student'),
        ),
        migrations.CreateModel(
            name='Contingency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursmentDate', models.DateField(default=datetime.date.today)),
                ('month', models.IntegerField(default=5)),
                ('year', models.IntegerField(default=2024)),
                ('amount', models.DecimalField(decimal_places=2, default=15000, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingency', to='api.student')),
            ],
            options={
                'ordering': ['student'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
