# Generated by Django 5.0.2 on 2024-05-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_contingencylogs_student_contingency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contingency',
            unique_together={('student', 'year')},
        ),
        migrations.RemoveField(
            model_name='contingency',
            name='month',
        ),
    ]
